### ISSUE TITLE
DockerImage with S3 Support available?

### ISSUE THREAD

**Issue by marcoschneidertui** [hyness/spring-cloud-config-server#16]
Hi,
I have just a very short question: are there any plans to provide the docker image with preconfigured AWSS3 as Configuration Storage?
That would be really great.
Best regards
Marco

**Comment by hyness** [comment]
The tricky part about adding individual features like S3 is adding them in a way that doesn't affect users that don't need the feature.  This request is similar to the other feature requests that are currently open.  This one might be easier since, I believe, Spring Cloud has a `@ConditionalOnAws` annotation that would make this safe to include.

**Comment by hyness** [comment]
The latest image has S3 support. Please give it a try. If you find an issue, please file a bug
