### ISSUE TITLE
Add basic http security for client accessing?

### ISSUE THREAD

**Issue by pvannuff** [hyness/spring-cloud-config-server#5]
This is handy dockerized spring cloud config server,  but I would really like to use some basic security for client accessing. Right now anybody can do requests to this setup and get everything, which might include passwords etc. (Having them encrypted in the underlying git repo obviously doesn't protect them in this use case.)

Could you add simple basic http security for clients, as touched upon briefly in http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.3.RELEASE/multi/multi__spring_cloud_config_server.html#_security ?

(@alzamabar asked the same on the docker hub page.)

**Comment by hyness** [comment]
I have been hesitant to add basic security to this image, because it requires adding more jars to the underlying jar backing this image.  Once it's added, it's cumbersome to disable, and require everyone to add settings that shouldn't be required.  I could add a `secure` branch and tags, but then that will double the burden of maintaining this image, make it more cumbersome to include, and require additional documentation for a feature I'm not convinced is needed for most use cases.

You mentioned @alzamabar's request on the docker hub, and I believe his issue was solved by using a secured github api token.  Do you really need to expose your config server?  In the deployments I use this image, we have a web accessible, secured private github or gitlab repository backing this image.  This image can then be linked to the containers that need it without making it web accessible.  Would this sort of strategy work for your use case?

**Comment by pvannuff** [comment]
I can see why you don't want to add all the extra stuff, I was thinking activating it would be optional anyway and could simply be activated by some config settings.

At the moment we're not actually using this container yet but we would like to use it outside of our docker environment as well. I was thinking of setting up some kind of allowed hosts filtering as an alternative. Not that straightforward to do with just some configuration for the embedded tomcat, it seems.
