### ISSUE TITLE
"created date" in dockerhub images is 42 years ago

### ISSUE THREAD

**Issue by paulfelton** [hyness/spring-cloud-config-server#86]
The images when pulled from docker hub have a creation date of "1980-01-01T00:00:01Z". 
![Capture](https://user-images.githubusercontent.com/3404356/167591525-90ed86f0-c678-46d7-8e2b-cd7585298b6c.JPG)

This leads to queries as to whether this is an up-to-date image, etc.

**Comment by hyness** [comment]
This project uses Cloud Native Buildpacks to create the OCI images.  `pack` creates images with timestamps like this for reproducible builds.  [See this comment](https://github.com/buildpacks/pack/issues/931#issuecomment-719524493) for further explanation.  Closing this issue as this is the expected behavior
