### ISSUE TITLE
What CMD to get terminal access for pod?

### ISSUE THREAD

**Issue by JustinSomers** [hyness/spring-cloud-config-server#96]
Hi, currently trying to debug my configuration and make sure files are passed over.  We also made some changes to this to run a configentry.sh script to move our settings into a docker file built on top of this.  However, looks like the image no longer contains an executable we can do (used to be /bin/sh it looks like).

**Comment by JustinSomers** [comment]
I keep encountering ` failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown`

With my docker file looking like:
```
FROM hyness/spring-cloud-config-server
# COPY ./application-gitlab.yml /opt/spring-cloud-config-server/application.yml

WORKDIR /config
COPY ./configentry.sh /opt/spring-cloud-config-server/configentry.sh
COPY ./application.properties /opt/spring-cloud-config-server/application.properties
COPY ./application.properties /config
ARG SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
ARG SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
ARG SERVER_PORT
ARG MANAGEMENT_SERVER_PORT

ENV SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
ENV SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
ENV SERVER_PORT ${SERVER_PORT}
ENV MANAGEMENT_SERVER_PORT ${MANAGEMENT_SERVER_PORT}
EXPOSE 4001


ENTRYPOINT ["sh", "/opt/spring-cloud-config-server/configentry.sh"]
```

**Comment by hyness** [comment]
Issues are for reporting bugs, requesting new features, not for asking questions about unrelated frameworks like Kubernetes (since you are referring to a pod) or your customization of this image. I’m not sure why you thought opening an issue was easier than a Google search, but none of what you’re asking about is supported by this project. Feel free to ask questions in the discussions section after doing some research on your own

**Comment by JustinSomers** [comment]
Hi, I've done plenty of research.  I'm mainly concerned as when trying to run the hyness/cspring-cloud-config-server image you used to be able to get a shell by running `docker exec -it [image-id] /bin/sh` to examine the contents of the container.  This is no longer the case in later images.   We were able to do this previously in `hyness/spring-cloud-config-server@sha256:d75904c7b9bb7cc72e08244f78cb3c1ea8ce87fc9fa1b2f2099c172575d24dfa`.

Generally you can run `docker inspect [container-id]` and examine the `cmd` property to see what shells it supports - however in this case their are none.

**Comment by hyness** [comment]
This project leverages Spring Boot’s built in support for building OCI images with Cloud Native Buildpacks. It’s effectively a distroless container, which is why you no longer see the /bin/sh process. This container is a lot more secure than the original docker builds we used to release, but one of the drawbacks is you cannot exec into the container any more.  More and more projects are starting to build containers like this either with Spring Boot or using Google’s distroless base image or Gib. 

I’ve seen you’ve already forked the project, so you can import the Dockerfile from the 3.0 branch and attempt to get that to build with the current version of the code.  It should work with the current code on main. The project has no plans to go back to docker builds.  Hope this helps
